@baseUrl = http://localhost:3000

# Notes
###List all notes

GET {{baseUrl}}/notes/
?limit=10
&offset=0
Authorization: Bearer 123456
###

###list one note
GET {{baseUrl}}/notes/1/
###

###Create a note
POST {{baseUrl}}/notes/
Content-Type: application/json

 {
    "text": "Oi Lucas",
    "fromId": 9,
    "forId": 6  
  }

### update a note
PATCH  {{baseUrl}}/notes/11
Content-Type: application/json

{
    "text": "oi duda update",
    "read": false
  }

###delete a note
DELETE {{baseUrl}}/notes/2/

#########################


#########################



####################User############


###List all Users
GET {{baseUrl}}/user/
?limit=100
&offset=100
###

###list one user
GET {{baseUrl}}/user/a/
###

###Create one user
POST {{baseUrl}}/user/
Content-Type: application/json

 {
    "email": "Duda@email.com" ,
    "password": "123456",
    "name": "Dudaa"
  }

### update a user
PATCH  {{baseUrl}}/user/6
Content-Type: application/json

{
  "password": "123456",
  "name": "Lucas"
  }

###delete a user
DELETE {{baseUrl}}/user/8/