@baseUrl = http://localhost:3000

@authToken = {{authenticate.response.body.acessToken}}

@refreshToken = {{authenticate.response.body.refreshToken}}
# Notes
###List all notes

GET {{baseUrl}}/notes/
?limit=10
&offset=0
Authorization: Bearer 123456
role: admin
###

###list one note
GET {{baseUrl}}/notes/4/
Authorization: Bearer {{authToken}}
###

###Create a note
POST {{baseUrl}}/notes/
Content-Type: application/json
Authorization: Bearer {{authToken}}

 {
    "text": "Novo recado",
    "forId": 1  
  }

### update a note
PATCH  {{baseUrl}}/notes/4
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "text": "oi duda update",
    "read": true
  }

###delete a note
DELETE {{baseUrl}}/notes/4/
Authorization: Bearer {{authToken}}

#########################


#########################



####################User############


###List all Users
GET {{baseUrl}}/user/
?limit=100
&offset=100
Authorization: Bearer {{authToken}}

###list one user
GET {{baseUrl}}/user/1/
Authorization: Bearer {{authToken}}
###

###Create one user
POST {{baseUrl}}/user/
Content-Type: application/json


 {
    "email": "Lucas6@email.com" ,
    "password": "123456",
    "name": "Lucas Souza"
  }

### update a user
PATCH  {{baseUrl}}/user/5
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "password": "123456",
  "name": "Lucas Atualizado"
  }

###delete a user
DELETE {{baseUrl}}/user/12/
Authorization: Bearer {{authToken}}



######AUTH#####

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "Lucas6@email.com",
  "password": "123456"
}


### RE-AUTH#####

# @name re-authenticate

POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}



######Upload#####
#####photo


POST {{baseUrl}}/user/upload-picture
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimiterHttp

------BoundaryDelimiterHttp
Content-Disposition: form-data; name="file"; filename="man.png"
Content-Type: image/png

< ./dev/images/man.png
------BoundaryDelimiterHttp--

###see photo

GET {{baseUrl}}/pictures/13.png